package com.example.myBlog.mapper;

import com.example.myBlog.entity.MyQuestion;
import com.example.myBlog.entity.MyQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MyQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    long countByExample(MyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int deleteByExample(MyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int insert(MyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int insertSelective(MyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    List<MyQuestion> selectByExampleWithRowbounds(MyQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    List<MyQuestion> selectByExample(MyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    MyQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyQuestion record, @Param("example") MyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByExample(@Param("record") MyQuestion record, @Param("example") MyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByPrimaryKeySelective(MyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByPrimaryKey(MyQuestion record);
}