package com.example.myBlog.mapper;

import com.example.myBlog.entity.myQuestion;
import com.example.myBlog.entity.myQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface myQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    long countByExample(myQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int deleteByExample(myQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int insert(myQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int insertSelective(myQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    List<myQuestion> selectByExampleWithRowbounds(myQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    List<myQuestion> selectByExample(myQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    myQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") myQuestion record, @Param("example") myQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int updateByExample(@Param("record") myQuestion record, @Param("example") myQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int updateByPrimaryKeySelective(myQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_QUESTION
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    int updateByPrimaryKey(myQuestion record);
}