package com.example.myBlog.mapper;

import com.example.myBlog.entity.MyUser;
import com.example.myBlog.entity.MyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    long countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    List<MyUser> selectByExampleWithRowbounds(MyUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    List<MyUser> selectByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    MyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByExample(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByPrimaryKeySelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYUSER
     *
     * @mbg.generated Thu Sep 26 21:28:26 CST 2019
     */
    int updateByPrimaryKey(MyUser record);
}