server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://10.9.148.16:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QLazy_311228
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:ORCLE
#    username: scott
#    password: tiger
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.myBlog.mapper
ucloud: 
  ufile: 
    private-key: 60a7fa2b-0998-4ab7-9d21-62e41dfde1a3
    public-key: TOKEN_1bed9846-9d87-44b3-8494-fcef505ad329
    bucket-name: qlazy
    proxy-suffix: ufileos.com
    region: cn-bj
    expires-duration: 315360000
logging:
  file: logs/community.log
  file.max-history: 30
  file.max-size: 200MB
  level:
    root: info
    
