spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: scott
    password: tiger
mybatis: 
  mapper-locations: Mapper.xml
  type-aliases-package: com.example.demo.Mapper
  

