package com.example.myBlog.entity;

public class MyComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.PARENT_ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.PARENT_TYPE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Integer parentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.COMMENTATOR
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Integer commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.GMT_CREATE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYCOMMENT.CONTENT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.ID
     *
     * @return the value of MYCOMMENT.ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.ID
     *
     * @param id the value for MYCOMMENT.ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.PARENT_ID
     *
     * @return the value of MYCOMMENT.PARENT_ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.PARENT_ID
     *
     * @param parentId the value for MYCOMMENT.PARENT_ID
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.PARENT_TYPE
     *
     * @return the value of MYCOMMENT.PARENT_TYPE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Integer getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.PARENT_TYPE
     *
     * @param parentType the value for MYCOMMENT.PARENT_TYPE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setParentType(Integer parentType) {
        this.parentType = parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.COMMENTATOR
     *
     * @return the value of MYCOMMENT.COMMENTATOR
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Integer getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.COMMENTATOR
     *
     * @param commentator the value for MYCOMMENT.COMMENTATOR
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setCommentator(Integer commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.GMT_CREATE
     *
     * @return the value of MYCOMMENT.GMT_CREATE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.GMT_CREATE
     *
     * @param gmtCreate the value for MYCOMMENT.GMT_CREATE
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.GMT_MODIFIED
     *
     * @return the value of MYCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.GMT_MODIFIED
     *
     * @param gmtModified the value for MYCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.LIKE_COUNT
     *
     * @return the value of MYCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.LIKE_COUNT
     *
     * @param likeCount the value for MYCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYCOMMENT.CONTENT
     *
     * @return the value of MYCOMMENT.CONTENT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYCOMMENT.CONTENT
     *
     * @param content the value for MYCOMMENT.CONTENT
     *
     * @mbg.generated Fri Sep 13 21:00:45 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

}