CREATE TABLE MYCOMMENT 
(
  ID INT NOT NULL 
, PARENT_ID INT NOT NULL 
, PARENT_TYPE INT NOT NULL 
, COMMENTATOR INT NOT NULL 
, GMT_CREATE INT NOT NULL 
, GMT_MODIFIED INT NOT NULL 
, LIKE_COUNT INT DEFAULT 0 
, CONTENT VARCHAR2(1024)
, CONSTRAINT TABLE2_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
//创建序列，使用方法MyComment_Id_Seq.Nextval
CREATE SEQUENCE MyComment_Id_Seq 
start with 1 
increment by 1;